title: StackBench
description: Benchmark coding agents on library-specific tasks through local deployment and open source community collaboration
url: https://docs.stackbench.ai
baseurl: ""

# Naptha branding
author: Naptha
naptha_url: https://naptha.ai
logo: /assets/naptha-logo.png

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Only show tutorials in navigation
header_pages:
  - tutorials/0.getting-started.md
  - tutorials/1.how-stackbench-works.md
  - tutorials/2.cli-commands.md

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "page"